tables:
  - schema: public
    table: company_category_keywords
    columns:
      - id
      - company_category_id
      - keyword_type
      - keywords
      - created_at
      - updated_at
    primary_key: id
    initial_value: "1970-01-01"
    cursor_column: updated_at
    updated_column: updated_at
    write_disposition: merge
    enabled: false