tables:
  - schema: public
    table: images
    columns:
      - id
      - caption
      - image_file
      - offer_data_images
      - create_time
      - update_time
      - position
      - translations_caption
    primary_key: id
    initial_value: "1970-01-01"
    cursor_column: create_time
    updated_column: update_time
    enabled: false

  - schema: public
    table: uploads
    columns:
      - id
      - filename
      - create_time
      - size
      - mime_type
      - url
      - update_time
      - origins_header_etag
      - origins_header_last_modified
      - origins_location
      - amount_of_refs
    primary_key: id
    initial_value: "1970-01-01"
    cursor_column: create_time
    updated_column: update_time
    enabled: false

  - schema: public
    table: revisions
    columns:
      - id
      - create_time
      - update_time
      - source
      - action
      - client_id
      - client_name
      - supplier_id
      - snapshot
      - offer_id
    primary_key: id
    initial_value: "1970-01-01"
    cursor_column: create_time
    updated_column: update_time
    enabled: false