tables:
  - schema: public
    table: images
    output_table_name: images
    enabled: true
    columns:
      - id
      - caption
      - image_file
      - offer_data_images
      - create_time
      - update_time
      - position
      - translations_caption
    cursor_column: dlt_cursor
    cursor_expression: GREATEST(create_time, update_time)

  - schema: public
    table: uploads
    output_table_name: uploads
    enabled: true
    columns:
      - id
      - filename
      - create_time
      - size
      - mime_type
      - url
      - update_time
      - origins_header_etag
      - origins_header_last_modified
      - origins_location
      - amount_of_refs
    cursor_column: dlt_cursor
    cursor_expression: GREATEST(create_time, update_time)

  - schema: public
    table: revisions
    output_table_name: supplier_offers_revisions
    enabled: true
    select_sql: |
      id::text AS id,
      create_time,
      update_time,
      "source" AS source,
      "action" AS action,
      client_id,
      client_name,
      supplier_id::text AS supplier_id,
      "snapshot"::text AS snapshot,
      offer_id::text AS offer_id
    output_columns:
      - id
      - create_time
      - update_time
      - source
      - action
      - client_id
      - client_name
      - supplier_id
      - snapshot
      - offer_id
      - dlt_cursor
    cursor_column: dlt_cursor
    cursor_expression: GREATEST(create_time, update_time)

  - schema: public
    table: offers
    output_table_name: offers
    enabled: true
    select_sql: |
      id::text as id,
      create_time,
      delete_time,
      update_time,
      publish_time,
      supplier_id::text as supplier_id,
      COALESCE(data_description, '') as data_description,
      data_name,
      data_language,
      COALESCE(data_keywords::text, '') as data_keywords,
      COALESCE(data_external_url, '') as data_external_url,
      COALESCE(data_areas_of_application::text, '') as data_areas_of_application,
      COALESCE(data_brands::text, '') as data_brands,
      COALESCE(data_colors::text, '') as data_colors,
      COALESCE(data_origins::text, '') as data_origins,
      COALESCE(data_materials::text, '') as data_materials,
      COALESCE(data_models::text, '') as data_models,
      COALESCE(data_standards::text, '') as data_standards,
      COALESCE(data_versions::text, '') as data_versions,
      COALESCE(data_ontology_concept_id, 0) as data_ontology_concept_id,
      COALESCE(data_company_category_id, 0) AS data_company_category_id,
      COALESCE(data_showcased, false) as data_showcased,
      COALESCE(slug_id, 0) as slug_id,
      COALESCE(data_cpv::text, '') as data_cpv,
      COALESCE(data_price_min, 0.00) as data_price_min,
      COALESCE(data_price_max, 0.00) as data_price_max,
      COALESCE(data_price_cur, '') as data_price_cur,
      COALESCE(data_moq_value, 0.00) as data_moq_value,
      COALESCE(data_moq_unit, '') as data_moq_unit,
      COALESCE(create_by, '') as create_by,
      COALESCE(data_translations_description::text, '') as data_translations_description,
      COALESCE(data_translations_keywords::text, '') as data_translations_keywords,
      COALESCE(data_translations_name::text, '') as data_translations_name,
      COALESCE(content_rating::text, '') as content_rating,
      COALESCE(data_price_kind, '') as data_price_kind,
      COALESCE(data_price_unit, '') as data_price_unit,
      COALESCE(create_by_source, '') as create_by_source
    output_columns:
      - id
      - create_time
      - delete_time
      - update_time
      - publish_time
      - supplier_id
      - data_description
      - data_name
      - data_language
      - data_keywords
      - data_external_url
      - data_areas_of_application
      - data_brands
      - data_colors
      - data_origins
      - data_materials
      - data_models
      - data_standards
      - data_versions
      - data_ontology_concept_id
      - data_company_category_id
      - data_showcased
      - slug_id
      - data_cpv
      - data_price_min
      - data_price_max
      - data_price_cur
      - data_moq_value
      - data_moq_unit
      - create_by
      - data_translations_description
      - data_translations_keywords
      - data_translations_name
      - content_rating
      - data_price_kind
      - data_price_unit
      - create_by_source
      - dlt_cursor
    cursor_column: dlt_cursor
    cursor_expression: GREATEST(create_time, update_time)