tables:
  - schema: public
    table: images
    output_table_name: images
    enabled: true
    columns:
      - id
      - caption
      - image_file
      - offer_data_images
      - create_time
      - update_time
      - position
      - translations_caption
    cursor_column: dlt_cursor
    cursor_expression: GREATEST(create_time, update_time)

  - schema: public
    table: uploads
    output_table_name: uploads
    enabled: true
    columns:
      - id
      - filename
      - create_time
      - size
      - mime_type
      - url
      - update_time
      - origins_header_etag
      - origins_header_last_modified
      - origins_location
      - amount_of_refs
    cursor_column: dlt_cursor
    cursor_expression: GREATEST(create_time, update_time)