tables:
  - schema: public
    table: companies
    columns:
      - customer_id
      - is_customer
      - name
      - employee_count_code
      - created_at
      - updated_at
      - company_categories
      - site_code
      - booked_site_codes
      - platforms
      - wlw_id
      - ep_id
      - uuid
    primary_key: uuid
    initial_value: "1970-01-01"
    cursor_column: created_at
    updated_column: updated_at
    enabled: false