tables:
  - schema: public
    table: sessions
    columns:
      - id
      - issued_at
      - expires_at
      - authenticated_at
      - identity_id
      - created_at
      - updated_at
      - token
      - active
      - nid
      - logout_token
      - aal
      - authentication_methods
    primary_key: id
    initial_value: "1970-01-01"
    cursor_column: created_at
    updated_column: updated_at
    enabled: false

  - schema: public
    table: identity_credentials
    columns:
      - id
      - config
      - identity_credential_type_id
      - identity_id
      - created_at
      - updated_at
      - nid
      - version
    primary_key: id
    initial_value: "1970-01-01"
    cursor_column: created_at
    updated_column: updated_at
    enabled: false

  - schema: public
    table: identity_verifiable_addresses
    columns:
      - id
      - status
      - via
      - verified
      - value
      - verified_at
      - identity_id
      - created_at
      - updated_at
      - nid
    primary_key: id
    initial_value: "1970-01-01"
    cursor_column: created_at
    updated_column: updated_at
    enabled: false

  - schema: public
    table: identity_credential_identifiers
    columns:
      - id
      - identifier
      - identity_credential_id
      - created_at
      - updated_at
      - nid
      - identity_credential_type_id
    primary_key: id
    initial_value: "1970-01-01"
    cursor_column: created_at
    updated_column: updated_at
    enabled: false

  - schema: public
    table: identities
    columns:
      - id
      - schema_id
      - traits
      - created_at
      - updated_at
      - nid
      - state
      - state_changed_at
      - metadata_public
      - metadata_admin
      - available_aal
      - organization_id
    primary_key: id
    initial_value: "1970-01-01"
    cursor_column: created_at
    updated_column: updated_at
    enabled: false