tables:
  - schema: public
    table: sessions
    output_table_name: user_kratos_sessions
    enabled: true
    columns:
      - id
      - issued_at
      - expires_at
      - authenticated_at
      - identity_id
      - created_at
      - updated_at
      - token
      - active
      - nid
      - logout_token
      - aal
      - authentication_methods
    cursor_column: dlt_cursor
    cursor_expression: GREATEST(created_at, updated_at)

  - schema: public
    table: identity_credentials
    output_table_name: user_kratos_identity_credentials
    enabled: true
    columns:
      - id
      - config
      - identity_credential_type_id
      - identity_id
      - created_at
      - updated_at
      - nid
      - version
    cursor_column: dlt_cursor
    cursor_expression: GREATEST(created_at, updated_at)

  - schema: public
    table: identity_verifiable_addresses
    output_table_name: user_kratos_identity_verifiable_addresses
    enabled: true
    columns:
      - id
      - status
      - via
      - verified
      - value
      - verified_at
      - identity_id
      - created_at
      - updated_at
      - nid
    cursor_column: dlt_cursor
    cursor_expression: GREATEST(created_at, updated_at)

  - schema: public
    table: identity_credential_identifiers
    output_table_name: user_kratos_identity_credential_identifiers
    enabled: true
    columns:
      - id
      - identifier
      - identity_credential_id
      - created_at
      - updated_at
      - nid
      - identity_credential_type_id
    cursor_column: dlt_cursor
    cursor_expression: GREATEST(created_at, updated_at)

  - schema: public
    table: identities
    output_table_name: user_kratos_identities
    enabled: true
    columns:
      - id
      - schema_id
      - traits
      - created_at
      - updated_at
      - nid
      - state
      - state_changed_at
      - metadata_public
      - metadata_admin
      - available_aal
      - organization_id
    cursor_column: dlt_cursor
    cursor_expression: GREATEST(created_at, updated_at)
