tables:
  - schema: public
    table: send_email_request
    output_table_name: send_email_request
    enabled: true
    columns:
      - id
      - caller_service_message_id
      - context_platform
      - context_service_origin
      - from_email
      - to_email
      - email_provider
      - email_provider_template_id
      - email_provider_custom_properties
      - email_provider_contact_properties
      - metadata
      - provider_message_id
      - status
      - created_at
      - sent_at
      - reply_to_email
      - caller_service_transaction_id
