tables:
  - schema: public
    table: contact_form_message_type_classification
    output_table_name: contact_form_message_type_classification
    enabled: true
    columns:
      - contact_form_message_id
      - predicted_message_type
      - user_given_message_type

  - schema: public
    table: contact_form_message
    output_table_name: contact_form_message
    enabled: true
    select_sql: |
      id::text AS id,
      COALESCE(sender_salutation, '') AS sender_salutation,
      COALESCE(sender_first_name, '') AS sender_first_name,
      COALESCE(sender_last_name, '') AS sender_last_name,
      COALESCE(sender_email, '') AS sender_email,
      COALESCE(sender_company_name, '') AS sender_company_name,
      COALESCE(sender_phone_number, '') AS sender_phone_number,
      COALESCE(receiver_email, '') AS receiver_email,
      COALESCE(receiver_company_id::text, '') AS receiver_company_id,
      is_private_request,
      COALESCE(message_type, '') AS message_type,
      COALESCE(subject, '') AS subject,
      regexp_replace(COALESCE(message, ''), E'[\r\n]+', ' ', 'g') AS message,
      COALESCE(status, '') AS status,
      COALESCE(request_received_at::text, '') AS request_received_at,
      COALESCE(email_send_at::text, '') AS email_send_at,
      is_spam,
      COALESCE(mail_provider, '') AS mail_provider,
      COALESCE(mail_provider_message_id, '') AS mail_provider_message_id,
      COALESCE(mail_provider_error_code::text, '') AS mail_provider_error_code,
      COALESCE(sender_full_name, '') AS sender_full_name,
      COALESCE("source", '') as source,
      COALESCE(status_reason, '') AS status_reason,
      COALESCE(conversation_id::text, '') AS conversation_id,
      COALESCE(mail_provider_status_id, '') AS mail_provider_status_id,
      COALESCE(mail_provider_status, '') AS mail_provider_status,
      COALESCE(mail_provider_send_result, '') AS mail_provider_send_result,
      product_id,
      COALESCE(test_id::text, '') AS test_id,
      COALESCE(metadata::text, '') AS metadata,
      COALESCE(offer_id::text, '') AS offer_id
    output_columns:
      - id
      - sender_salutation
      - sender_first_name
      - sender_last_name
      - sender_email
      - sender_company_name
      - sender_phone_number
      - receiver_email
      - receiver_company_id
      - is_private_request
      - message_type
      - subject
      - message
      - status
      - request_received_at
      - email_send_at
      - is_spam
      - mail_provider
      - mail_provider_message_id
      - mail_provider_error_code
      - sender_full_name
      - source
      - status_reason
      - conversation_id
      - mail_provider_status_id
      - mail_provider_status
      - mail_provider_send_result
      - product_id
      - test_id
      - metadata
      - offer_id

  - schema: public
    table: one_platform_direct_requests_status
    output_table_name: one_platform_direct_requests_status
    enabled: true
    select_sql: |
      id::text as id,
      request_iteration_object::text as request_iteration_object,
      created_at,
      updated_at
    output_columns:
      - id
      - request_iteration_object
      - created_at
      - updated_at

  - schema: public
    table: analytics_qdr_to_rfq
    output_table_name: analytics_qdr_to_rfq
    enabled: true
    columns:
      - request_id
      - direct_request_to_rfq_request_object
      - created_at
      - updated_at
      - version

  - schema: public
    table: reply_message
    output_table_name: reply_message
    enabled: true
    select_sql: |
      id::text AS id,
      COALESCE(conversation_id::text, '') AS conversation_id,
      COALESCE(is_first_reply, false) AS is_first_reply,
      COALESCE(sender_user_id::text, '') AS sender_user_id,
      COALESCE(sender_user_email, '') AS sender_user_email,
      COALESCE(receiver_user_id::text, '') AS receiver_user_id,
      COALESCE(receiver_user_email, '') AS receiver_user_email,
      COALESCE(event_received_at::text, '') AS event_received_at,
      COALESCE(email_send_at::text, '') AS email_send_at,
      COALESCE(mail_provider, '') AS mail_provider,
      COALESCE(mail_provider_message_id, '') AS mail_provider_message_id,
      COALESCE(mail_provider_error_code::text, '') AS mail_provider_error_code,
      COALESCE(status, '') AS status,
      COALESCE(status_reason, '') AS status_reason,
      COALESCE(mail_provider_status_id::text, '') AS mail_provider_status_id,
      COALESCE(mail_provider_status, '') AS mail_provider_status,
      COALESCE(mail_provider_send_result, '') AS mail_provider_send_result,
      regexp_replace(COALESCE(message_content, ''), E'[\r\n]+', ' ', 'g') AS message_content,
      COALESCE(metadata::text, '') AS metadata
    output_columns:
      - id
      - conversation_id
      - is_first_reply
      - sender_user_id
      - sender_user_email
      - receiver_user_id
      - receiver_user_email
      - event_received_at
      - email_send_at
      - mail_provider
      - mail_provider_message_id
      - mail_provider_error_code
      - status
      - status_reason
      - mail_provider_status_id
      - mail_provider_status
      - mail_provider_send_result
      - message_content
      - metadata