tables:
  - schema: public
    table: push_notification
    enabled: false

  - schema: public
    table: purchaser_request
    enabled: false
    select_sql: |
      id,
      user_uuid,
      message_type,
      request_type,
      REPLACE(REPLACE(message, E'\n', ' '), E'\r', ' ') AS message,
      created_at,
      company_id,
      product_id,
      transaction_id,
      rfq_id,
      user_source,
      profile_id

  - schema: public
    table: supplier_user_setting
    enabled: false
    columns:
      - id
      - user_id
      - device_id
      - general_push_notification
      - request_push_notification
      - visitor_push_notification
      - is_active
      - push_notification_token
      - created_at
      - updated_at
      - locale
      - email
      - user_source
      - enable_purchaser_notification
      - company_ids

  - schema: public
    table: user_setting
    enabled: false

  - schema: public
    table: ab_test_record
    enabled: false
    columns:
      - id
      - mobile_session_id
      - experiment_name
      - experiment_variant
      - recorded_at

  - schema: public
    table: user_categories
    enabled: false

  - schema: public
    table: feedback
    enabled: false
    select_sql: |
      id,
      email,
      subject,
      REPLACE(REPLACE(message, E'\n', ' '), E'\r', ' ') AS message,
      created_at,
      updated_at,
      application_source