tables:
  - schema: public
    table: push_notification
    output_table_name: push_notification
    enabled: true
    select_sql: |
      id::text as id,
      user_id,
      de_message,
      delivered,
      message_read,
      created_at,
      updated_at,
      hash_id,
      reference_number,
      notification_source,
      notification_type,
      en_message,
      device_id,
      email,
      user_source,
      company_id,
      conversation_id,
      sender_id,
      message_from,
      profile_id,
      sender_profile_id,
      user_setting_uuid::text as user_setting_uuid
    output_columns:
      - id
      - user_id
      - de_message
      - delivered
      - message_read
      - created_at
      - updated_at
      - hash_id
      - reference_number
      - notification_source
      - notification_type
      - en_message
      - device_id
      - email
      - user_source
      - company_id
      - conversation_id
      - sender_id
      - message_from
      - profile_id
      - sender_profile_id
      - user_setting_uuid

  - schema: public
    table: purchaser_request
    output_table_name: purchaser_request
    enabled: true
    select_sql: |
      id::text as id,
      user_uuid,
      message_type,
      request_type,
      REPLACE(REPLACE(message, E'\n', ' '), E'\r', ' ') AS message,
      created_at,
      company_id,
      product_id,
      transaction_id,
      rfq_id,
      user_source,
      profile_id
    output_columns:
      - id
      - user_uuid
      - message_type
      - request_type
      - message
      - created_at
      - company_id
      - product_id
      - transaction_id
      - rfq_id
      - user_source
      - profile_id

  - schema: public
    table: supplier_user_setting
    output_table_name: supplier_user_setting
    enabled: true
    columns:
      - id
      - user_id
      - device_id
      - general_push_notification
      - request_push_notification
      - visitor_push_notification
      - is_active
      - push_notification_token
      - created_at
      - updated_at
      - locale
      - email
      - user_source
      - enable_purchaser_notification
      - company_ids

  - schema: public
    table: user_setting
    output_table_name: user_setting
    enabled: true

  - schema: public
    table: ab_test_record
    output_table_name: ab_test_record
    enabled: true
    columns:
      - id
      - mobile_session_id
      - experiment_name
      - experiment_variant
      - recorded_at

  - schema: public
    table: user_categories
    output_table_name: user_categories
    enabled: true

  - schema: public
    table: feedback
    output_table_name: feedback
    enabled: true
    select_sql: |
      id,
      email,
      subject,
      REPLACE(REPLACE(message, E'\n', ' '), E'\r', ' ') AS message,
      created_at,
      updated_at,
      application_source
    output_columns:
      - id
      - email
      - subject
      - message
      - created_at
      - updated_at
      - application_source