tables:
  - schema: public
    table: verticals
    output_table_name: verticals
    enabled: true
    select_sql: |
      id,
      "name",
      slug,
      created_at,
      updated_at,
      array_to_json(company_category_ids)::text as company_category_ids
    output_columns:
      - id
      - name
      - slug
      - created_at
      - updated_at
      - company_category_ids

  - schema: public
    table: concepts
    output_table_name: concepts
    enabled: true
    columns:
      - id
      - name
      - created_at
      - updated_at
      - label
      - terms_count
      - user_facing
      - vertical_id
      - is_phrase

  - schema: public
    table: terms
    output_table_name: terms
    enabled: true
    columns:
      - id
      - concept_id
      - kind
      - name
      - created_at
      - updated_at
      - numerus
      - language
      - normalized_name

  - schema: public
    table: properties
    output_table_name: properties
    enabled: true
    columns:
      - id
      - name
      - value
      - concept_id
      - tag_id
      - created_at
      - updated_at