tables:
  - schema: public
    table: visable_pserp_switch_query_batch
    enabled: false
    columns:
      - site_id
      - batch_name
      - search_term

  - schema: public
    table: visable_predict_cate
    enabled: false
    columns:
      - normilized_search_term
      - cat_id
      - cat_1v_id
      - cat_1v_name
      - cat_2v_id
      - cat_2v_name
      - cat_3v_id
      - cat_3v_name
      - cat_4v_id
      - cat_4v_name