tables:
  - schema: public
    table: supplier_visitors_counts_mv
    output_table_name: supplier_visitors_count
    enabled: true
    select_sql: |
      supplier_uuid::text AS supplier_uuid,
      visitors_yesterday,
      visitors_last_30_days,
      visitors_last_12_months,
      regexp_replace(last_visitor_name, E'[\r\n]+', ' ', 'g') AS last_visitor_name,
      regexp_replace(last_visitor_address, E'[\r\n]+', ' ', 'g') AS last_visitor_address,
      last_visitor_country
    output_columns:
      - supplier_uuid
      - visitors_yesterday
      - visitors_last_30_days
      - visitors_last_12_months
      - last_visitor_name
      - last_visitor_address
      - last_visitor_country