tables:
  - schema: public
    table: customer_pixels
    output_table_name: customer_pixels
    enabled: true
    select_sql: |
      id,
      company_id,
      customer_id,
      identifier,
      domain,
      company_name,
      created_at,
      updated_at,
      status,
      activated_at,
      deactivated_at,
      supplier_uuid::text as supplier_uuid,
      visitor_company_id,
      had_traffic,
      domain_changed_at,
      last_activity,
      first_activity,
      ep_id,
      automatic_status_updates_disabled,
      monthly_limit,
      day_limit,
      paused
    output_columns:
      - id
      - company_id
      - customer_id
      - identifier
      - domain
      - company_name
      - created_at
      - updated_at
      - status
      - activated_at
      - deactivated_at
      - supplier_uuid
      - visitor_company_id
      - had_traffic
      - domain_changed_at
      - last_activity
      - first_activity
      - ep_id
      - automatic_status_updates_disabled
      - monthly_limit
      - day_limit
      - paused