tables:
  - schema: public
    table: report_published_drafts
    output_table_name: report_published_drafts
    enabled: true
    columns:
      - import_task_id
      - draft_id
      - offer_id
      - published_at
      - created_at

  - schema: public
    table: offers
    output_table_name: supplier_onboarding_offers
    enabled: true
    select_sql: |
      offer_id::text as offer_id,
      supplier_id,
      COALESCE(product_details::text, '') as product_details,
      COALESCE(create_by, '') as create_by,
      published,
      deleted,
      created_at,
      updated_at,
      status,
      COALESCE(origin_product_id, '') as origin_product_id,
      COALESCE(array_to_json(platforms)::text, '[]') as platforms
    output_columns:
      - offer_id
      - supplier_id
      - product_details
      - create_by
      - published
      - deleted
      - created_at
      - updated_at
      - status
      - origin_product_id
      - platforms
