tables:
  - schema: public
    table: companies
    output_table_name: companies
    enabled: true
    columns:
      - customer_id
      - is_customer
      - name
      - employee_count_code
      - created_at
      - updated_at
      - company_categories
      - site_code
      - booked_site_codes
      - platforms
      - wlw_id
      - ep_id
      - uuid
